loginPage:
  path: /login/{code}
  controller: Ewll\UserBundle\Controller\UserController::loginPage
  defaults: {code: null}
  methods: [GET]
login:
  path: /login
  controller: Ewll\UserBundle\Controller\UserController::login
  methods: [POST]
signupPage:
  path: /signup
  controller: Ewll\UserBundle\Controller\UserController::signupPage
  methods: [GET]
signup:
  path: /signup
  controller: Ewll\UserBundle\Controller\UserController::signup
  methods: [POST]
exit:
  path: /exit
  controller: Ewll\UserBundle\Controller\UserController::exit
