main:
  path: /
  controller: Ewll\UserBundle\Controller\UserController::mainPage
  methods: [GET]
login.page:
  path: /login/{tokenCode}
  controller: Ewll\UserBundle\Controller\UserController::loginPage
  defaults: {tokenCode: null}
  methods: [GET]
login:
  path: /login
  controller: Ewll\UserBundle\Controller\UserController::login
  methods: [POST]
oauth:
  path: /oauth/{name}
  controller: Ewll\UserBundle\Controller\OauthController::oauth
  methods: [GET]
oauth.signup:
  path: /oauth/signup
  controller: Ewll\UserBundle\Controller\OauthController::signup
  methods: [POST]
#oauth.login:
#  path: /oauth/login
#  controller: Ewll\UserBundle\Controller\OauthController::login
#  methods: [POST]
signupPage:
  path: /signup
  controller: Ewll\UserBundle\Controller\UserController::signupPage
  methods: [GET]
twofa.page.set:
  path: /2fa/{tokenCode}
  controller: Ewll\UserBundle\Controller\TwofaController::page
  methods: [GET]
twofa.page.login-confirm:
  path: /2fa/login/{tokenCode}
  controller: Ewll\UserBundle\Controller\TwofaController::loginConfirmPage
  methods: [GET]
twofa.enroll.code:
  path: /2fa/enroll-code
  controller: Ewll\UserBundle\Controller\TwofaController::enrollCode
  methods: [POST]
twofa.enroll.code-telegram:
  path: /2fa/enroll-code/telegram
  controller: Ewll\UserBundle\Controller\TwofaController::enrollCodeTelegram
  methods: [POST]
twofa.enroll:
  path: /2fa/enroll
  controller: Ewll\UserBundle\Controller\TwofaController::enroll
  methods: [POST]
twofa.login.code:
  path: /2fa/login/code
  controller: Ewll\UserBundle\Controller\TwofaController::loginCode
  methods: [POST]
twofa.login:
  path: /2fa/login
  controller: Ewll\UserBundle\Controller\TwofaController::login
  methods: [POST]
#twofa.oauth.code:
#  path: /2fa/oauth/code
#  controller: Ewll\UserBundle\Controller\TwofaController::oauthCode
#  methods: [POST]
signup:
  path: /signup
  controller: Ewll\UserBundle\Controller\UserController::signup
  methods: [POST]
passwordRecovering:
  path: /password-recovering
  controller: Ewll\UserBundle\Controller\UserController::passwordRecoveringPage
  methods: [GET]
passwordRecovering.init:
  path: /password-recovering/init
  controller: Ewll\UserBundle\Controller\UserController::passwordRecoveringInit
  methods: [POST]
passwordRecovering.finishPage:
  path: /password-recovering/{tokenCode}
  controller: Ewll\UserBundle\Controller\UserController::passwordRecoveringFinishPage
  methods: [GET]
passwordRecovering.recover:
  path: /password-recovering/recover
  controller: Ewll\UserBundle\Controller\UserController::passwordRecoveringRecover
  methods: [POST]
exit:
  path: /exit
  controller: Ewll\UserBundle\Controller\UserController::exit
